import { parseSnapshot } from "./model/diff";
import { DEFAULT_SETTINGS, DEFAULT_TYPE_ORDER, PropType, Settings, Snapshot } from "./model/types";

// Plugin data keys
export const SOURCE_ID_KEY = "sourceComponentId"; // on the table: ID of its component
export const VERSION_KEY = "propTableVersion"; // on the table: "2"
export const SNAPSHOT_KEY = "snapshot"; // on the table: Snapshot JSON
export const TABLE_ID_KEY = "propTableId"; // on a local component: ID of its table (v1 key)
const SETTINGS_KEY = "settings"; // on figma.root

export const NOTE_PREFIX = "Note:";
export const REMOVED_NOTE_PREFIX = "Removed note:";
export const NOTE_PLACEHOLDER = "Add a note…";

// --- Settings ---

export function loadSettings(): Settings {
  let saved: Partial<Settings> = {};
  try {
    saved = JSON.parse(figma.root.getPluginData(SETTINGS_KEY) || "{}");
  } catch {
    saved = {};
  }
  return normalizeSettings(saved);
}

export function normalizeSettings(saved: Partial<Settings>): Settings {
  const d = DEFAULT_SETTINGS;
  const typeOrder = Array.isArray(saved.typeOrder)
    ? [
        ...saved.typeOrder.filter((t): t is PropType => DEFAULT_TYPE_ORDER.includes(t as PropType)),
        ...DEFAULT_TYPE_ORDER.filter((t) => !(saved.typeOrder as string[]).includes(t)),
      ]
    : d.typeOrder;
  return {
    theme: saved.theme === "dark" ? "dark" : "light",
    accent: typeof saved.accent === "string" && /^#[0-9a-f]{6}$/i.test(saved.accent) ? saved.accent : d.accent,
    font: typeof saved.font === "string" && saved.font.trim() ? saved.font.trim() : d.font,
    columns: { ...d.columns, ...(saved.columns || {}) },
    sections: { ...d.sections, ...(saved.sections || {}) },
    typeOrder,
    placement: saved.placement === "below" ? "below" : "right",
    changeMarks: saved.changeMarks ?? d.changeMarks,
    lintMarks: saved.lintMarks ?? d.lintMarks,
  };
}

export function saveSettings(settings: Partial<Settings>): Settings {
  const normalized = normalizeSettings(settings);
  figma.root.setPluginData(SETTINGS_KEY, JSON.stringify(normalized));
  return normalized;
}

export function resetSettings(): Settings {
  figma.root.setPluginData(SETTINGS_KEY, "");
  return loadSettings();
}

// --- Table ↔ component links ---

export function isTable(node: BaseNode): node is FrameNode {
  return node.type === "FRAME" && !!node.getPluginData(SOURCE_ID_KEY);
}

export function getSnapshot(table: FrameNode): Snapshot | null {
  return parseSnapshot(table.getPluginData(SNAPSHOT_KEY));
}

export function linkTable(
  table: FrameNode,
  component: ComponentNode | ComponentSetNode,
  snapshot: Snapshot
): void {
  table.setPluginData(SOURCE_ID_KEY, component.id);
  table.setPluginData(VERSION_KEY, "2");
  table.setPluginData(SNAPSHOT_KEY, JSON.stringify(snapshot));
  table.setRelaunchData({ generate: "" });
  // Library (remote) components are read-only.
  if (!component.remote) {
    component.setPluginData(TABLE_ID_KEY, table.id);
    component.setRelaunchData({ generate: "" });
  }
}

/** Walk up from a node to the table generated by this plugin, if any. */
export function findTableAncestor(node: BaseNode): FrameNode | null {
  let current: BaseNode | null = node;
  while (current && current.type !== "PAGE" && current.type !== "DOCUMENT") {
    if (isTable(current)) return current;
    current = current.parent;
  }
  return null;
}

export async function findExistingTable(component: ComponentNode | ComponentSetNode): Promise<FrameNode | null> {
  const tableId = component.getPluginData(TABLE_ID_KEY);
  if (tableId) {
    const node = await figma.getNodeByIdAsync(tableId);
    if (node && node.type === "FRAME" && !node.removed) return node;
  }
  const match = figma.currentPage.findAllWithCriteria({ types: ["FRAME"], pluginData: { keys: [SOURCE_ID_KEY] } });
  return match.find((n) => n.getPluginData(SOURCE_ID_KEY) === component.id) ?? null;
}

/** Every table on the given pages, including v1 tables linked only from their component. */
export async function findAllTables(pages: readonly PageNode[]): Promise<FrameNode[]> {
  const found = new Map<string, FrameNode>();
  for (const page of pages) {
    for (const t of page.findAllWithCriteria({ types: ["FRAME"], pluginData: { keys: [SOURCE_ID_KEY] } })) {
      found.set(t.id, t);
    }
    const v1Owners = page.findAllWithCriteria({
      types: ["COMPONENT", "COMPONENT_SET"],
      pluginData: { keys: [TABLE_ID_KEY] },
    });
    for (const owner of v1Owners) {
      const table = await figma.getNodeByIdAsync(owner.getPluginData(TABLE_ID_KEY));
      if (table && table.type === "FRAME" && !table.removed && !found.has(table.id)) {
        // Give v1 tables the table-side link so they can be updated like v2 tables.
        table.setPluginData(SOURCE_ID_KEY, owner.id);
        found.set(table.id, table);
      }
    }
  }
  return [...found.values()];
}

// --- Notes ---

/** Read notes typed on a table so they survive a rebuild. */
export function readNotes(table: FrameNode): Record<string, string> {
  const notes: Record<string, string> = {};
  const texts = table.findAllWithCriteria({ types: ["TEXT"] });
  for (const t of texts) {
    let id: string | null = null;
    if (t.name.startsWith(NOTE_PREFIX)) id = t.name.slice(NOTE_PREFIX.length);
    else if (t.name.startsWith(REMOVED_NOTE_PREFIX)) id = t.name.slice(REMOVED_NOTE_PREFIX.length);
    if (id === null) continue;
    const text = t.characters.trim();
    if (text && text !== NOTE_PLACEHOLDER) notes[id] = text;
  }
  return notes;
}
